2403 2425 add indexing and search on more embed attributes
NDLANO/search-api pull request #135
Opened 2021-02-04 13:31 UTC by haattis

2021-02-05 06:46 UTC, gunnarvelle reviewed
Veldig bra med alle testene som sjekker søketreff!

2021-02-05 06:46 UTC, gunnarvelle commented on src/main/scala/no/ndla/searchapi/service/search/MultiDraftSearchService.scala
> +          simpleStringQuery(queryString).field("embedIds", 3),
Usikker med boostinga her. Dette vekter jo treff på disse verdiene like høgt som tittel slik at ved relevanssortering så dukker treffa opp tidlig. Det gir kanskje meining om du skriver inn en videoid, men samtidig vil treff på en videoid gi få treff så du treng kanskje ikkje den høgere boosten.

2021-02-05 14:33 UTC, gunnarvelle approved these changes
LGTM

2021-02-08 06:05 UTC, jnatten requested changes
Litt pirk :)

2021-02-08 06:05 UTC, jnatten commented on src/main/scala/no/ndla/searchapi/service/search/MultiDraftSearchService.scala
> +      })
Jeg syns det ser ut som disse kanskje burde vært filtere istedet for `simpleStringQuery`'er. Kan det stemme?

2021-02-08 06:05 UTC, jnatten commented on src/main/scala/no/ndla/searchapi/service/search/MultiSearchService.scala
> +      })
Samme spørsmålet om filtere her :)

2021-02-08 13:31 UTC, jnatten commented on src/main/scala/no/ndla/searchapi/service/search/MultiSearchService.scala
> +              idsQuery(q)
Kan ikke disse fjernes når de er flyttet til filter delen av querien? :smile:

2021-02-08 13:51 UTC, haattis commented on src/main/scala/no/ndla/searchapi/service/search/MultiSearchService.scala
> +              idsQuery(q)
Det skal være mulig å få treff på embedIds og embedResources fra query-parameter også, så må vel ha både dette og filter.

2021-02-09 05:51 UTC, jnatten commented on src/main/scala/no/ndla/searchapi/service/search/MultiSearchService.scala
> +              idsQuery(q)
åja hmm. Hva slags treff tenker vi på da? Bare nøyaktige eller skal de være "søkbare"?

Hvis det siste burde vi sikkert gå tilbake til `simpleStringQuery` siden `termQuery` kun gir  treff på nøyaktig, men da burde vel også feltene tokenizes med et `textField` i tillegg også?

2021-02-09 07:43 UTC, haattis commented on src/main/scala/no/ndla/searchapi/service/search/MultiSearchService.scala
> +              idsQuery(q)
Nøyaktige treff på query-parameter også.

2021-02-09 08:23 UTC, gunnarvelle commented on src/main/scala/no/ndla/searchapi/service/search/MultiSearchService.scala
> +              idsQuery(q)
Tanken er at det skal være mulig å skrive inn en videoid fra brightcove og få treff på artikkelen som har akkurat den iden.

2021-02-09 10:09 UTC, jnatten commented on src/main/scala/no/ndla/searchapi/service/search/MultiSearchService.scala
> +              idsQuery(q)
Ait da er det jo perf :+1:

2021-02-09 10:09 UTC, jnatten approved these changes
LGTM :100:

2021-02-09 12:20 UTC, merged